storePassword=123321
keyPassword=123321
keyAlias=sheikhismailalkurdi
storeFile=sheikhismailalkurdi.jks

#  keytool -genkey -v -keystore android/app/sheikhismailalkurdi.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias sheikhismailalkurdi -keypass 123321 -storepass 123321


#  keytool -list -v -keystore android/app/sheikhismailalkurdi.jks -alias sheikhismailalkurdi -storepass 123321 -keypass 123321


#  keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
